// Локализация
export const translations = {
    ru: {
        title: "Планировщик зданий альянса",
        buildingsHeader: "Здания ⇆",
        buildingsListHeader: "Список зданий",
        modalTitle: "Имя игрока",
        renameModalTitle: "Переименовать замок",
        gridSizeLabel: "Размер сетки:",
        apply: "Применить",
        save: "Сохранить", // Общая кнопка "Сохранить"
        fortress: "Крепость альянса",
        outpost: "Форпост альянса",
        hellgates: "Адские врата",
        hospital: "Госпиталь",
        farm: "Ферма",
        warehouse: "Склад",
        castle: "Замок игрока",
        deadzone: "Мертвая зона",
        rename: "Переименовать",
        delete: "Удалить",
        playerName: "Имя игрока",
        saveButton: "Сохранить", // Кнопка для шаринга состояния
        rotateGrid: "Повернуть сетку",
        resetRotation: "Сбросить поворот",
        distanceToHGLabel: "До Адских Врат", // Текст для кнопки
        distanceUnit: "", // Единица измерения расстояния (клеток)
        hellgatesNotPlaced: "Врата не установлены",
        cannotShiftFurther: "Невозможно сдвинуть здания дальше.",
    },
    en: {
        title: "Alliance Buildings Planner",
        buildingsHeader: "Buildings ⇆",
        buildingsListHeader: "Buildings List",
        modalTitle: "Player Name",
        renameModalTitle: "Rename Castle",
        gridSizeLabel: "Grid Size:",
        apply: "Apply",
        save: "Save", // General save button
        fortress: "Alliance Fortress",
        outpost: "Alliance Outpost",
        hellgates: "Hell Gates",
        hospital: "Hospital",
        farm: "Farm",
        warehouse: "Warehouse",
        castle: "Player Castle",
        deadzone: "Dead Zone",
        rename: "Rename",
        delete: "Delete",
        playerName: "Player Name",
        saveButton: "Save", // Button for sharing state
        rotateGrid: "Rotate Grid",
        resetRotation: "Reset Rotation",
        distanceToHGLabel: "To Hell Gates", // Text for the button
        distanceUnit: "cells", // Distance unit
        hellgatesNotPlaced: "Gates not placed",
        cannotShiftFurther: "Cannot shift buildings further.",
    },
    pt_br: { // Португальский (Бразилия)
        title: "Planejador de Construções da Aliança",
        buildingsHeader: "Construções",
        buildingsListHeader: "Lista de Construções",
        modalTitle: "Nome do Jogador",
        renameModalTitle: "Renomear Castelo",
        gridSizeLabel: "Tamanho da Grade:",
        apply: "Aplicar",
        save: "Salvar",
        fortress: "Fortaleza da Aliança",
        outpost: "Posto Avançado da Aliança",
        hellgates: "Portões Infernais",
        hospital: "Hospital",
        farm: "Fazenda",
        warehouse: "Armazém",
        castle: "Castelo do Jogador",
        deadzone: "Zona Morta",
        rename: "Renomear",
        delete: "Excluir",
        playerName: "Nome do Jogador",
        saveButton: "Salvar", // Для кнопки "поделиться состоянием"
        defaultCastleNamePrefix: "Castelo ",
        rotateGrid: "Girar Grade",
        resetRotation: "Resetar Rotação",
        distanceToHGLabel: "Aos Portões Infernais",
        distanceUnit: "células",
        hellgatesNotPlaced: "Portões não colocados",
        cannotShiftFurther: "Não é possível mover mais as construções."
    },
    de: { // Немецкий
        title: "Allianz Gebäudeplaner",
        buildingsHeader: "Gebäude",
        buildingsListHeader: "Gebäudeliste",
        modalTitle: "Spielername",
        renameModalTitle: "Burg umbenennen",
        gridSizeLabel: "Rastergröße:",
        apply: "Anwenden",
        save: "Speichern",
        fortress: "Allianzfestung",
        outpost: "Außenposten der Allianz",
        hellgates: "Höllentore",
        hospital: "Krankenhaus",
        farm: "Farm",
        warehouse: "Lagerhaus",
        castle: "Spielerburg",
        deadzone: "Todeszone",
        rename: "Umbenennen",
        delete: "Löschen",
        playerName: "Spielername",
        saveButton: "Speichern", // Для кнопки "поделиться состоянием"
        defaultCastleNamePrefix: "Burg ",
        rotateGrid: "Raster drehen",
        resetRotation: "Drehung zurücksetzen",
        distanceToHGLabel: "Zu den Höllentoren",
        distanceUnit: "Felder",
        hellgatesNotPlaced: "Tore nicht platziert",
        cannotShiftFurther: "Gebäude können nicht weiter verschoben werden."
    },
};

// Конфигурация зданий
export const buildingConfig = {
    fortress: { icon: '🏰', size: 3, areaSize: 15, limit: 1, type: 'alliance' },
    outpost: { icon: '🚩', size: 2, areaSize: 10, limit: 5, type: 'alliance' },
    hellgates: { icon: '👹', size: 3, areaSize: 0, limit: 1, type: 'alliance' },
    hospital: { icon: '🏥', size: 2, areaSize: 0, limit: 1, type: 'alliance' },
    farm: { icon: '🌾', size: 2, areaSize: 0, limit: 1, type: 'alliance' },
    warehouse: { icon: '🏭', size: 2, areaSize: 0, limit: 1, type: 'alliance' },
    castle: { icon: '🏯', size: 2, areaSize: 0, limit: -1, type: 'player' },
    deadzone: { icon: '⚠️', size: 1, areaSize: 0, limit: -1, type: 'special', bgcolor: 'rgba(144, 238, 144, 0.5)' },
};